site_name: RAdwords
pages:
- home: index.md
- quickstart guide: quickstart.md
- installation: install.md
- requirements: requirements.md
- workflow:
    - authentication: auth.md
    - querybuilder: query.md
    - load data: getdata.md
    - reports and metrics: reports.md
- code examples: examples.md
- FAQ / troubleshooting: faq.md
theme: readthedocs